# Deploy keycloak           
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 8090
    targetPort: 8090
    nodePort: 30001
  selector:
    app: keycloak
  type: LoadBalancer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:17.0.1
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"
        ports:
        - name: http
          containerPort: 8090
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8090

---
# Deploy application

apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-api
spec:
  selector:
    matchLabels:
      app: microservices-api
  template:
    metadata:
      labels:
        app: microservices-api
    spec:
      containers:
      - name: microservices-api
        image: brunotrind4d3/microservices-api:v1
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: microservices-api
spec:
  selector:
    app: microservices-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  type: NodePort
