#Deploy PostgresSQL


# Deploy application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-api
spec:
  selector:
    matchLabels:
      app: microservices-api
  template:
    metadata:
      labels:
        app: microservices-api
    spec:
      containers:
        - name: microservices-api
          image: brunotrind4d3/microservices-api:v1
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: microservices-api
spec:
  selector:
    app: microservices-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  type: NodePort
