foo:
    bar: ${project.version}
application:
    name: ${project.name}
    version: ${project.version}

spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: http://localhost:8090/realms/microservices/protocol/openid-connect/token