foo:
    bar: ${project.version}
application:
    name: ${project.name}
    version: ${project.version}

keycloak:
    auth-server-url: http://localhost:8090/
    realm: microservices
    resource: user-microservices
    public-client: true

spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: http://localhost:8090/realms/microservices/protocol/openid-connect/token